### ISSUE TITLE
Adapting v3 for Durham...

### ISSUE THREAD

**Issue by timstallmann** [tobinbradley/quality-of-life-dashboard#1]
Hey @tobinbradley! This version is awesome, I'm so appreciating all the work you've done with it... 

I'm working with John K. on porting over version 3.0 to Durham County, and am running into some difficulties implementing a geography switcher (we have data at Blockgroup, Tract & Neighborhood levels and want to allow users to switch geographies). I think I've got most of the way there but keep getting these errors of the form `Error: The layer 'neighborhood' does not exist in the map's style and cannot be styled.` -- do you have any idea offhand of what might be causing that?

**Comment by tobinbradley** [comment]
I'm doing a whole lot of speculating on what you might have changed. YMMV.

This message is coming from Mapbox GL JS. It's saying that you're trying to change the styling on a layer called 'neighborhood' and it doesn't have a layer called neighborhood. I'm guessing that's a layer you added (?). The layer names I'm using are 'neighborhoods' and 'neighborhoods-fill-extrude'. Best guess is you are removing/adding layers and it's trying to style something before it has adding it.

I'd suggest rather than removing and adding layers, change the source data. I.e. - 

`map.getSource('neighborhoods').setData(newGeoJSON);`

As 'neighborhoods' is the source for the two layers, you aren't getting stuck in layer transit. Otherwise you'll have to set `if (map.getLayer('neighborhood'))` blocks around all of your styling code.

**Comment by timstallmann** [comment]
Aha that approach makes so much more sense, thanks! Tl;dr I'm adding a `GeographySwitcher` component, storying `appState.geographyId` and then both the GeoJSON files and metric data have filenames which are keyed to the geography ID. But I had been trying to add new layers for each base geography (`tract`, `blockgroup`, `neighborhood`) and then hide/show them depending on the current geography ID. 

Keeping 1 layer and swapping out the GeoJSON seems like it might work better; will try that instead!
