### ISSUE TITLE
QOL Data

### ISSUE THREAD

**Issue by wilsongis** [tobinbradley/quality-of-life-dashboard#5]
Would it be better to add the QOL Data as a submodule rather than create recursive repos?

git submodule add -f https://github.com/tobinbradley/mecklenburg-quality-of-life-data.git data

**Comment by tobinbradley** [comment]
You could do it that way. You'll end up at the same place with more typing, but using submodules is arguably syntactically neater. I don't do it for the dashboard because the mecklenburg data repo isn't a static dependency for other users (i.e. ideally at some point you'll want to use your own data repo). But as long as you remember to `git submodule deinit` the mecklenburg data repo before you swap in your own, I can't see any problems with it. Have at it!

**Comment by wilsongis** [comment]
I was just curious. I forked the Mecklenburg data repo and using the submodule of it.
